# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw
    ports:
      - "3306:3306"
    volumes:
      - /home/krzysiek/volumes/mariaDb:/var/lib/mysql
    networks:
      mariadb-network:
        ipv4_address: 172.21.1.1

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      mariadb-network:
        ipv4_address: 172.21.1.2

networks:
  mariadb-network:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16